FROM gradle:7-jdk11-alpine as builder
USER root
WORKDIR /builder
ADD . /builder
RUN gradle build --stacktrace


FROM adoptopenjdk/openjdk11:jre-11.0.19_7
WORKDIR /app
EXPOSE 8080
COPY --from=builder /builder/build/libs/writer-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "writer-0.0.1-SNAPSHOT.jar"]